/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;

import java.io.FileNotFoundException;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void testgenerateError_noErrors() throws FileNotFoundException {
        String path = "./src/test/resources/noerrors.js";
        assertEquals("There should be no errors in the input file", App.generateError(path), "");
    }

    @Test public void testgenerateError_oneError() throws FileNotFoundException {
        String path = "./src/test/resources/oneerror.js";
        assertEquals("Error on line 7", App.generateError(path), "Line 7: Missing semicolon.\n");
    }

    @Test public void testgenerateError_fewErrors() throws FileNotFoundException {
        String path = "./src/test/resources/fewerrors.js";
        assertEquals("Error on lines 3, 14, 25", App.generateError(path), "Line 3: Missing semicolon.\nLine 14: Missing semicolon.\nLine 25: Missing semicolon.\n");
    }

    @Test public void testgenerateError_manyErrors() throws FileNotFoundException {
        String path = "./src/test/resources/manyerrors.js";
        assertEquals("Error on lines 7, 12, 25, 29, 31, 42, 47, 53, 54, 55", App.generateError(path), "Line 7: Missing semicolon.\nLine 12: Missing semicolon.\nLine 25: Missing semicolon.\nLine 29: Missing semicolon.\nLine 31: Missing semicolon.\nLine 42: Missing semicolon.\nLine 47: Missing semicolon.\nLine 53: Missing semicolon.\nLine 54: Missing semicolon.\nLine 55: Missing semicolon.\n");
    }

    @Test public void testgenerateError_emptyFile() throws FileNotFoundException {
        String path = "./src/test/resources/empty.js";
        assertEquals("There should be no errors in the input file", App.generateError(path), "");
    }

}
