/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Scanner;
import java.io.FileNotFoundException;

public class App {

    public static void main(String[] args) throws FileNotFoundException {
        String path = "./src/main/resources/gates.js";
        String errors = generateError(path);
        System.out.println("Errors" + errors);
        if (errors != "") {
            System.out.println(errors.trim());
        } else {
            System.out.println("No errors in file");
        }

    }
    public static String generateError(String filePath) throws FileNotFoundException {
        Scanner s = null;
        String newString = "";
        String returnString = "";
        int lineNumber = 0;
        s = new Scanner(new BufferedReader(new FileReader(filePath)));
        while (s.hasNextLine()) {
            lineNumber++;
            newString = s.nextLine();
            if ((!newString.endsWith(";")) && (!newString.endsWith("}")) && (!newString.endsWith("{")) && (!newString.isEmpty()) && (!newString.contains("if")) && (!newString.contains("else"))) {
                returnString = returnString + "Line " + lineNumber + ": Missing semicolon.\n";
            }
        }
        return returnString;
    }
}
